spring.application.name=core
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{transactionId}] %-5level %logger{36} - %msg%n
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,metrics,prometheus
spring.profiles.default=local
