spring.application.name=core
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.data-locations=\
classpath:sql/users.sql,\
classpath:sql/training_types.sql,\
classpath:sql/trainees.sql,\
classpath:sql/trainers.sql,\
classpath:sql/trainee_trainers.sql,\
classpath:sql/trainings.sql
spring.jpa.defer-datasource-initialization=true
#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{transactionId}] %-5level %logger{36} - %msg%n