spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm_stg
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.sql.init.mode=never
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL}
spring.activemq.user=${ACTIVEMQ_USER}
spring.activemq.password=${ACTIVEMQ_PASSWORD}
