spring.application.name=core
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{transactionId}] %-5level %logger{36} - %msg%n
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,metrics,prometheus
spring.profiles.default=local
security.jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdKd3RTZWNyZXRLZXlGb3JIUzI1Ng==
security.jwt.expiration=3600000
security.token.cleanup-interval=3600000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=5
resilience4j.circuitbreaker.instances.trainerWorkloadService.sliding-window-size=5
resilience4j.circuitbreaker.instances.trainerWorkloadService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.trainerWorkloadService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.trainerWorkloadService.wait-duration-in-open-state=10s
