spring.application.name=trainer-workload-service
server.port=8081
security.jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdKd3RTZWNyZXRLZXlGb3JIUzI1Ng==
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{transactionId}] %-5level %logger{36} - %msg%n
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
app.messaging.trainer-workload-queue=trainer.workload.queue
